name: graphmert
channels:
  - defaults
dependencies:
  - defaults/linux-64::_libgcc_mutex==0.1=main
  - defaults/linux-64::ca-certificates==2025.12.2=h06a4308_0
  - defaults/linux-64::ld_impl_linux-64==2.44=h153f514_2
  - defaults/linux-64::libgomp==15.2.0=h4751f2c_7
  - defaults/linux-64::python_abi==3.13=3_cp313
  - defaults/noarch::tzdata==2025b=h04d1e81_0
  - defaults/linux-64::_openmp_mutex==5.1=1_gnu
  - defaults/linux-64::libgcc==15.2.0=h69a1729_7
  - defaults/linux-64::libgcc-ng==15.2.0=h166f726_7
  - defaults/linux-64::libstdcxx==15.2.0=h39759b7_7
  - defaults/linux-64::bzip2==1.0.8=h5eee18b_6
  - defaults/linux-64::libexpat==2.7.3=h7354ed3_4
  - defaults/linux-64::libmpdec==4.0.0=h5eee18b_0
  - defaults/linux-64::libstdcxx-ng==15.2.0=hc03a8fd_7
  - defaults/linux-64::libuuid==1.41.5=h5eee18b_0
  - defaults/linux-64::libzlib==1.3.1=hb25bd0a_0
  - defaults/linux-64::ncurses==6.5=h7934f7d_0
  - defaults/linux-64::openssl==3.0.18=hd6dcaed_0
  - defaults/linux-64::pthread-stubs==0.3=h0ce48e5_1
  - defaults/linux-64::xorg-libxau==1.0.12=h9b100fa_0
  - defaults/linux-64::xorg-libxdmcp==1.1.5=h9b100fa_0
  - defaults/linux-64::xorg-xorgproto==2024.1=h5eee18b_1
  - defaults/linux-64::xz==5.6.4=h5eee18b_1
  - defaults/linux-64::libffi==3.4.4=h6a678d5_1
  - defaults/linux-64::libxcb==1.17.0=h9b100fa_0
  - defaults/linux-64::readline==8.3=hc2a1206_0
  - defaults/linux-64::zlib==1.3.1=hb25bd0a_0
  - defaults/linux-64::sqlite==3.51.1=he0a8d7e_0
  - defaults/linux-64::xorg-libx11==1.8.12=h9b100fa_1
  - defaults/linux-64::tk==8.6.15=h54e0aa7_0
  - defaults/linux-64::python==3.13.11=hcf712cf_100_cp313
  - defaults/linux-64::setuptools==80.9.0=py313h06a4308_0
  - defaults/linux-64::wheel==0.45.1=py313h06a4308_0
  - defaults/noarch::pip==25.3=pyhc872135_0
  - ipykernel
prefix: /scratch/gpfs/JHA/mb5157/CONDA/envs/graphmert
